name: Deploy

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: ${{ secrets.IP }}
          password: ${{ secrets.PRIVATE_PASSWORD }}
          script: 'cd /var/www/wase-physics && ./deploy.sh && ./deploy-docs.sh'